# -*- coding: utf-8 -*-
from django.conf.urls import url
from django.views.generic import TemplateView

from . import views


app_name = 'better_together_community_engine'
urlpatterns = [
    url(
        regex="^Person/~create/$",
        view=views.PersonCreateView.as_view(),
        name='Person_create',
    ),
    url(
        regex="^Person/(?P<pk>\d+)/~delete/$",
        view=views.PersonDeleteView.as_view(),
        name='Person_delete',
    ),
    url(
        regex="^Person/(?P<pk>\d+)/$",
        view=views.PersonDetailView.as_view(),
        name='Person_detail',
    ),
    url(
        regex="^Person/(?P<pk>\d+)/~update/$",
        view=views.PersonUpdateView.as_view(),
        name='Person_update',
    ),
    url(
        regex="^Person/$",
        view=views.PersonListView.as_view(),
        name='Person_list',
    ),
	url(
        regex="^Group/~create/$",
        view=views.GroupCreateView.as_view(),
        name='Group_create',
    ),
    url(
        regex="^Group/(?P<pk>\d+)/~delete/$",
        view=views.GroupDeleteView.as_view(),
        name='Group_delete',
    ),
    url(
        regex="^Group/(?P<pk>\d+)/$",
        view=views.GroupDetailView.as_view(),
        name='Group_detail',
    ),
    url(
        regex="^Group/(?P<pk>\d+)/~update/$",
        view=views.GroupUpdateView.as_view(),
        name='Group_update',
    ),
    url(
        regex="^Group/$",
        view=views.GroupListView.as_view(),
        name='Group_list',
    ),
	url(
        regex="^Membership/~create/$",
        view=views.MembershipCreateView.as_view(),
        name='Membership_create',
    ),
    url(
        regex="^Membership/(?P<pk>\d+)/~delete/$",
        view=views.MembershipDeleteView.as_view(),
        name='Membership_delete',
    ),
    url(
        regex="^Membership/(?P<pk>\d+)/$",
        view=views.MembershipDetailView.as_view(),
        name='Membership_detail',
    ),
    url(
        regex="^Membership/(?P<pk>\d+)/~update/$",
        view=views.MembershipUpdateView.as_view(),
        name='Membership_update',
    ),
    url(
        regex="^Membership/$",
        view=views.MembershipListView.as_view(),
        name='Membership_list',
    ),
	url(
        regex="^Invitation/~create/$",
        view=views.InvitationCreateView.as_view(),
        name='Invitation_create',
    ),
    url(
        regex="^Invitation/(?P<pk>\d+)/~delete/$",
        view=views.InvitationDeleteView.as_view(),
        name='Invitation_delete',
    ),
    url(
        regex="^Invitation/(?P<pk>\d+)/$",
        view=views.InvitationDetailView.as_view(),
        name='Invitation_detail',
    ),
    url(
        regex="^Invitation/(?P<pk>\d+)/~update/$",
        view=views.InvitationUpdateView.as_view(),
        name='Invitation_update',
    ),
    url(
        regex="^Invitation/$",
        view=views.InvitationListView.as_view(),
        name='Invitation_list',
    ),
	url(
        regex="^Role/~create/$",
        view=views.RoleCreateView.as_view(),
        name='Role_create',
    ),
    url(
        regex="^Role/(?P<pk>\d+)/~delete/$",
        view=views.RoleDeleteView.as_view(),
        name='Role_delete',
    ),
    url(
        regex="^Role/(?P<pk>\d+)/$",
        view=views.RoleDetailView.as_view(),
        name='Role_detail',
    ),
    url(
        regex="^Role/(?P<pk>\d+)/~update/$",
        view=views.RoleUpdateView.as_view(),
        name='Role_update',
    ),
    url(
        regex="^Role/$",
        view=views.RoleListView.as_view(),
        name='Role_list',
    ),
	]
