# Generated by Django 3.0.6 on 2020-05-06 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('better_together', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('joinable_id', 'joinable_content_type_id', 'member_id', 'member_content_type_id', 'role_id', 'role_content_type_id')},
        ),
    ]
