# Generated by Django 3.0.5 on 2020-04-28 20:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('better_together', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='group',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invitation',
            name='end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='end'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 28, 20, 11, 35, 448338, tzinfo=utc), verbose_name='start'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membership',
            name='end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='end'),
        ),
        migrations.AddField(
            model_name='membership',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 28, 20, 11, 48, 81668, tzinfo=utc), verbose_name='start'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='person',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='role',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='role',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='name'),
            preserve_default=False,
        ),
    ]
